### ISSUE TITLE
Operator precedence means u16_as_u8 drops high byte, repeats low byte

### ISSUE THREAD

**Issue by Thra11** [wezm/ssd1675#12]
https://github.com/wezm/ssd1675/blob/388f586ae439cc93f784e913273514c1cd0966e4/src/command.rs#L176-L178

I believe that `>>` has higher precendence than `&` (based on printing out values and the [docs](https://doc.rust-lang.org/reference/expressions.html#expression-precedence)), meaning that the high-byte expression need parentheses: `((val & 0xFF00) >> 8) as u8`, otherwise if shifts `0xFF00`, resulting in `0xFF`, then does the bitwise-and. This produces the result I'm seeing when I run the code, which is the low byte repeated, instead of the high byte followed by the low byte.

(I've been adapting your code to work with the larger 300x400 pixel display. I've _just_ got it working, so I'll share the results as soon as I've tidied them up and committed them.)

**Comment by wezm** [comment]
Wow that's unfortunate, nice find. This confirms it:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=195749e2d16c2db226e9d7a0d55db93e

Now that it's stable, this function can be removed in favour of [to_be_bytes](https://doc.rust-lang.org/std/primitive.u16.html#method.to_be_bytes).

**Comment by wezm** [comment]
I opened a PR with a fix. https://github.com/wezm/ssd1675/pull/13 I'm not set up to test on an actual device at the moment, so I haven't been able to test it there.

If you have time I would appreciate a quick look over the changes.
